CREATE TABLE temp_user(
    pk SERIAL PRIMARY KEY,
    c1 VARCHAR(50) NOT NULL,
    c2 VARCHAR(20) NOT NULL
);


ALTER TABLE temp_user ADD COLUMN google_id VARCHAR NOT NULL UNIQUE;

ALTER TABLE temp_user ADD COLUMN email VARCHAR NOT NULL;
ALTER TABLE temp_user ADD COLUMN name VARCHAR;
ALTER TABLE temp_user ADD COLUMN picture TEXT;
ALTER TABLE temp_user ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TiMESTAMP;